// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorldService.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace EnvoyGrpcService {
  public static partial class HelloWorldService
  {
    static readonly string __ServiceName = "EnvoyGrpcService.HelloWorldService";

    static readonly grpc::Marshaller<global::EnvoyGrpcService.HelloWorldRequest> __Marshaller_HelloWorldRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EnvoyGrpcService.HelloWorldRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EnvoyGrpcService.HelloWorldResponse> __Marshaller_HelloWorldResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EnvoyGrpcService.HelloWorldResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::EnvoyGrpcService.HelloWorldRequest, global::EnvoyGrpcService.HelloWorldResponse> __Method_SayHelloWorld = new grpc::Method<global::EnvoyGrpcService.HelloWorldRequest, global::EnvoyGrpcService.HelloWorldResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHelloWorld",
        __Marshaller_HelloWorldRequest,
        __Marshaller_HelloWorldResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EnvoyGrpcService.HelloWorldServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloWorldService</summary>
    public abstract partial class HelloWorldServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::EnvoyGrpcService.HelloWorldResponse> SayHelloWorld(global::EnvoyGrpcService.HelloWorldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloWorldService</summary>
    public partial class HelloWorldServiceClient : grpc::ClientBase<HelloWorldServiceClient>
    {
      /// <summary>Creates a new client for HelloWorldService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloWorldServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloWorldService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloWorldServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloWorldServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloWorldServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::EnvoyGrpcService.HelloWorldResponse SayHelloWorld(global::EnvoyGrpcService.HelloWorldRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloWorld(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EnvoyGrpcService.HelloWorldResponse SayHelloWorld(global::EnvoyGrpcService.HelloWorldRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHelloWorld, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EnvoyGrpcService.HelloWorldResponse> SayHelloWorldAsync(global::EnvoyGrpcService.HelloWorldRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloWorldAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EnvoyGrpcService.HelloWorldResponse> SayHelloWorldAsync(global::EnvoyGrpcService.HelloWorldRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHelloWorld, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloWorldServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloWorldServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloWorldServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHelloWorld, serviceImpl.SayHelloWorld).Build();
    }

  }
}
#endregion
